const data = {
    products: [
        {
            _id:'1',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'2',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'3',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 0,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'4',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'5',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 1,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'6',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'7',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        {
            _id:'8',
            name:'Camisa social xadrex',
            category:'Camisa',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 9,
            brand:'Lacoste',
            rating:  4.5,
            numReviews: 10,
            description:'Camisa manga longa Lacoste',
        },
        
    ],
};
export default data;